<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * @file
 * Contains players.module.
 */
/**
 * Implements hook_theme().
 */
function players_theme($existing, $type, $theme, $path): array
{
  return [
    'node__club__teaser' => [
      'template' => 'node--club--teaser',
      'base hook' => 'node',
      'path' => $path . '/templates',
    ],
    'views_view_fields__latest_published_players_by_competition__page_1' => [
      'render element' => 'elements',
      'template' => 'views-view-fields--latest-published-players-by-competition--page-1',
      'base hook' => 'views_view',
    ],
    'federation_list' => [
      'variables' => [
        'federations' => [],
      ],
    ],
    'competition_list' => [
      'variables' => [
        'competitions' => [],
        'federation' => [],
      ],
    ],
    'players_list' => [
      'variables' => [
        'federation' => [],
        'competition' => [],
        'players' => [],
      ],
    ],
    'latest_players_by_competition' => [
      'variables' => [
        'players' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function players_form_alter(&$form, FormStateInterface $form_state, $form_id): void
{
  if ($form_id == 'user_login_form') {
    $form['#submit'][] = 'players_user_login_redirect';
  }

  if ($form_id == 'node_player_form' || $form_id == 'node_player_edit_form') {
    $form['#attached']['library'][] = 'players/player_club';
  }

  if (in_array($form_id, ['node_competition_edit_form', 'node_competition_form'])) {
    $form['#validate'][] = 'players_competition_date_validation';
  }

  if ($form_id == 'player_registration_form') {
    $form['#validate'][] = 'players_check_competition_max_players';
  }
}

function players_user_login_redirect(&$form, FormStateInterface $form_state): void
{
  $account = \Drupal::currentUser();
  if ($account->hasRole('federation_admin')) {
    $form_state->setRedirect('players.federation_competitions');
  }

  if ($account->hasRole('competition_admin')) {
    $form_state->setRedirect('players.published_federations');
  }

  if ($account->hasRole('ihf_editor')) {
    $url = Url::fromUri('internal:/manage-content');
    $form_state->setRedirectUrl($url);
  }
}

function players_competition_date_validation($form, FormStateInterface $form_state): void
{
  $start_date = $form_state->getValue(['field_start_date', 0, 'value']);
  $end_date = $form_state->getValue(['field_end_date', 0, 'value']);

  $start_timestamp = strtotime($start_date);
  $end_timestamp = strtotime($end_date);

  if ($end_timestamp <= $start_timestamp) {
    $form_state->setErrorByName('field_end_date', t('The end date must be after the start date.'));
  }
}

/**
 * Implements hook_install().
 */
function players_install()
{
  // Create the federation field for users.
  FieldStorageConfig::create([
    'field_name' => 'field_admin_federation',
    'entity_type' => 'user',
    'type' => 'entity_reference',
    'settings' => ['target_type' => 'taxonomy_term'],
  ])->save();

  FieldConfig::create([
    'field_name' => 'field_admin_federation',
    'entity_type' => 'user',
    'bundle' => 'user',
    'label' => 'Federation',
    'settings' => [
      'handler' => 'default:taxonomy_term',
      'handler_settings' => [
        'target_bundles' => ['federation' => 'federation'],
      ],
    ],
  ])->save();
}

function players_check_competition_max_players(&$form, FormStateInterface $form_state): void
{
  $values = $form_state->getValues();

  if (Drupal\players\Helpers\Helper::isCompetitionFull($values['competition_id'])) {
    $form_state->setRedirect('players.federation_competition_players', [
      'competition_id' => $values['competition_id'],
      'federation_id' => $values['federation'],
    ]);
  }
}
